package sys

const (
	SERVERIMG         string = "htttp://localhost/imagenes/"
	CBASE             string = "siniv"
	CTIM              string = "tim"
	CESTADO           string = "estado"
	CMILITAR          string = "militar"
	CFAMILIAR         string = "familiar"
	CPERSONA          string = "persona"
	CCOMPONENTE       string = "componente"
	CRECIBO           string = "recibo"
	CINTEGRAL         string = "cuidadointegral"
	CREEMBOLSO        string = "reembolso"
	CAPOYO            string = "apoyo"
	CCARTAAVAL        string = "cartaaval"
	CFACTURA          string = "factura"
	CFEVIDA           string = "fevida"
	CTRATAMIENTO      string = "tratamiento"
	CTRAZA            string = "traza"
	CTRAZACIS         string = "trazacis"
	CCATEGORIA        string = "categoria"
	CUSUARIO          string = "usuario"
	WUSUARIO          string = "wusuario"
	CREDUCCION        string = "reduccion"
	CTAREASPENDIENDTE string = "tareaspendientes"
	CCONCEPTO         string = "conceptos"
	CMEDIDAJUDICIAL   string = "medidajudicial"
	CTORRETA          string = "torreta"
	CDOSA             string = "dosa"
	CAUXILIAR         string = "auxiliar"
	CCOMERCIAL        string = "comercial"
	CADMINISTRACION   string = "administracion"
	CRECAUDACION      string = "recaudacion"
	HTTPAPISYBASE     string = "http://192.168.41.24/ws_sybase/Webservices/index.php/api/"
)
